[package]
name = "first-class-variants"
version = "0.1.1"
authors = ["Ari Lotter <arilotter@gmail.com>"]
edition = "2018"


[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"

[lib]
proc-macro = true